inherit: 
    - models/mamba_small.yaml
    - wandb.yaml

model:
    n_dims: 128
    n_positions: 256

training:
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 50000
    train_steps: 200001
    curriculum:
        dims:
            start: 5
            end: 127
            inc: 2
            interval: 2000
